// Generated by scripts/build-image-manifest.mjs
export const HERO_IMAGES = [
  "/Codex%20SWC%20Photos/Main%20Hero.JPG",
  "/Codex%20SWC%20Photos/DJI_0045.JPG",
  "/Codex%20SWC%20Photos/DJI_0024.JPG"
]

export const GALLERY_IMAGES = [
  "/Codex%20SWC%20Photos/Commercial.jpg",
  "/Codex%20SWC%20Photos/DJI_0024.JPG",
  "/Codex%20SWC%20Photos/DJI_0045.JPG",
  "/Codex%20SWC%20Photos/DJI_0070.JPG",
  "/Codex%20SWC%20Photos/DJI_0078.JPG",
  "/Codex%20SWC%20Photos/IMG_0880.jpeg",
  "/Codex%20SWC%20Photos/Main%20Hero.JPG",
  "/Codex%20SWC%20Photos/Solar%20Panel%20.jpeg",
  "/Codex%20SWC%20Photos/Window%20Clean.jpeg",
  "/Codex%20SWC%20Photos/photo01.jpg",
  "/Codex%20SWC%20Photos/photo02.jpg",
  "/Codex%20SWC%20Photos/photo03.jpg",
  "/Codex%20SWC%20Photos/photo04.jpg",
  "/Codex%20SWC%20Photos/photo05.jpg",
  "/Codex%20SWC%20Photos/photo07.jpg",
  "/Codex%20SWC%20Photos/photo08.jpg",
  "/Codex%20SWC%20Photos/photo09.jpg",
  "/Codex%20SWC%20Photos/photo10.jpg",
  "/Codex%20SWC%20Photos/photo11.jpg",
  "/Codex%20SWC%20Photos/photo12.jpg"
]

export const TEAM_IMAGES = []

export const SERVICE_IMAGES = {
  "window": "/Codex%20SWC%20Photos/Window%20Clean.jpeg",
  "gutter": "/Codex%20SWC%20Photos/website-photos/DJI_0045.JPG",
  "conservatory": "/Codex%20SWC%20Photos/website-photos/DJI_0056.JPG",
  "solar": "/Codex%20SWC%20Photos/Solar%20Panel%20.jpeg",
  "fascias": "/Codex%20SWC%20Photos/website-photos/DJI_0078.JPG",
  "commercial": "/Codex%20SWC%20Photos/Commercial.jpg"
}

// Somerset Council logo from official website
export const SOMERSET_COUNCIL_LOGO = "https://www.somerset.gov.uk/assets/images/somerset-council-logo.svg"
