// Generated by scripts/build-image-manifest.mjs
export const SWC_LOGO = "/images/logos/SWC narrow Logo.jpg"

export const HERO_IMAGES = [
  "/images/photos/Main Hero.JPG",
  "/images/logos/logo.png",
  "/images/photos/DJI_0024.JPG"
]

export const GALLERY_IMAGES = [
  "/images/photos/DJI_0047.JPG",
  "/images/photos/DJI_0064.JPG",
  "/images/photos/DJI_0070.JPG",
  "/images/photos/DJI_0092.JPG",
  "/images/photos/IMG_0880.jpeg",
  "/images/photos/Vans.jpeg"
]

export const TEAM_IMAGES = [
  "/images/photos/Gutter Clearing.jpg"
]

export const SERVICE_IMAGES = {
  "window": "/images/photos/Window Clean.jpeg",
  "gutter": "/images/photos/Gutter Clearing.jpg",
  "gutter_clearing": "/images/photos/Gutter Clearing.jpg",
  "conservatory": "/images/photos/DJI_0052.JPG",
  "solar": "/images/photos/Solar Panel .jpeg",
  "fascias": "/images/photos/DJI_0045.JPG",
  "commercial": "/images/photos/Commercial.jpg",
  "pureWaterCleaning": "/images/photos/photo03.jpg"
}
