name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build application
      run: npm run build
    
    - name: Run Playwright tests
      run: npx playwright test
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-screenshots
        path: test-results/
        retention-days: 30

  # Frontend Changes Validation Job
  frontend-validation:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build application
      run: npm run build
    
    - name: Run Frontend Changes Tests
      run: npx playwright test frontend-changes.spec.ts
    
    - name: Generate Test Report
      if: always()
      run: |
        echo "# Frontend Changes Test Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        if [ -f "test-results/results.json" ]; then
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Tests failed or incomplete" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Validated Changes:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Logo seamless header integration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Three red dots in hero tagline" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Somerset Council logo removed from Recent Work" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Service image mappings use proper photos" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Cross-browser logo compatibility" >> $GITHUB_STEP_SUMMARY
    
    - name: Upload Frontend Test Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-validation-screenshots
        path: test-results/
        retention-days: 30